### ISSUE TITLE
アドバイス

### ISSUE THREAD

**Issue by 2vg** [sekihan02/Simple_Nim_Crawler#1]
どうしても言いたかったのでIssueに書いておきます

- [htmlparser](https://nim-lang.org/docs/htmlparser.html)を使うと正規表現に頼らないで分かりやすく書けると思います
- Nimはデフォルトで文字列はUTF-8しか扱ってません。他のエンコードは[encodings](https://nim-lang.org/docs/encodings.html)を使って変換したり出来ます
- httpsでも使えるようにnim.cfgを作って-d:sslと定義しておくといいかもしれません

**Comment by sekihan02** [comment]
すごく有難うございます。
行き当たりばったりに[Nim Manual](https://nim-lang.org/docs/manual.html)でしのぎながら進めているため非常に助かります。
githubも入門者なので、ここにお礼を書いて伝わるものなのかもわかっていないですが
すごく参考にします。有難うございました

**Comment by 2vg** [comment]
いえいえ！！何かあればTwitterの@mfqnにでもリプライで言ってください ;)

私が書いた日本語ドキュメントも使ってやってください！！

[Nim-World](https://2vg.github.io/Nim-World)
